GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('hephaestus_forge')
        .category('hephaestus')
        .setEUIO('in') // Machine takes power IN
        .setMaxIOSize(12, 4, 4, 4) // 4 Item In, 1 Item Out, 2 Fluid In
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)	

    allthemods.create('soul_extractor')
        .category('soul_extractor')
        .setEUIO('in') // Machine takes power IN
        .setMaxIOSize(12, 4, 4, 4) // 4 Item In, 1 Item Out, 2 Fluid In
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)	
})

GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('hephaestus_forge', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('hephaestus_forge') 
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()            
            .aisle('   HHH   ','   CCC   ', '         ', '         ', '         ')
            .aisle(' HHHIHHH ',' CCCCCCC ', '    G    ', '    G    ', '    C    ')
            .aisle(' HIHHHIH ',' CCCCCCC ', '  G   G  ', '  G   G  ', '  C   C  ')            
            .aisle('HHHHJHHHH','CCCCCCCCC', '         ', '         ', '         ')
            .aisle('HIHJIJHIH','CCCCCCCCC', ' G  A  G ', ' G     G ', ' C     C ')
			.aisle('HHHHJHHHH','CCCCCCCCC', '         ', '         ', '         ')
            .aisle(' HIHHHIH ',' CCCCCCC ', '  G   G  ', '  G   G  ', '  C   C  ')
			.aisle(' HHHIHHH ',' CCCCCCC ', '    G    ', '    G    ', '    C    ')
			.aisle('   HHH   ','   CKC   ', '         ', '         ', '         ')			
            .where('H', Predicates.blocks('forbidden_arcanus:polished_darkstone'))            
            .where('I', Predicates.blocks('forbidden_arcanus:arcane_chiseled_polished_darkstone'))            
            .where('J', Predicates.blocks('forbidden_arcanus:chiseled_arcane_polished_darkstone'))                        
            .where('A', Predicates.blocks('forbidden_arcanus:hephaestus_forge'))            
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('botania:bifrost_perm'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))	
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
			)
            .where(' ', Predicates.air()) 
            .build()
        )
		.workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')
    
        allthemods.create('soul_extractor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('soul_extractor') 
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()                        
            .aisle(' CCCCCCC ', ' G  G  G ', ' G  G  G ', ' G  G  G ', ' CCCCCCC ')            
            .aisle('CCCCCCCCC', 'G       G', 'G       G', 'G       G', 'CCCCCCCCC')
            .aisle('CCCCCCCCC', '         ', '         ', '         ', 'CCCCCCCCC')
			.aisle('CCCCCCCCC', 'G       G', 'G       G', 'G       G', 'CCCCCCCCC')
            .aisle(' CCCKCCC ', ' G  G  G ', ' G  G  G ', ' G  G  G ', ' CCCCCCC ')			
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('botania:bifrost_perm'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))	
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
			)
            .where(' ', Predicates.air()) 
            .build()
        )
		.workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')			
})

//Item.of('forbidden_arcanus:hephaestus_forge', '{BlockStateTag:{tier:5}}')