
GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('sanguine_ritual')
        .category('sanguine_ritual')
        .setEUIO('in') // Machine takes power IN
        .setMaxIOSize(16, 16, 1, 1) // Item In, Item Out, Fluid In, Fluid Out
        .setProgressBar(GuiTextures.COMPRESSOR_OVERLAY, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.COMPRESSOR)
})

GTCEuStartupEvents.registry('gtceu:machine', allthemods => {    
    allthemods.create('sanguine_ritual', 'multiblock')        
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('sanguine_ritual')         
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start() 
            .aisle('CCCCCCCCCCC', 'CGGGGGGGGGC', 'CUUUUUUUUUC', 'C         C', 'C         C', 'C         C', 'C         C', 'C         C')
            .aisle('CRRRRCRRRRC', 'G         G', 'UHHH   HHHU', '  UUUUUUU  ', '           ', '           ', '           ', '           ')
            .aisle('CRRRRCRRRRC', 'G         G', 'UHRH   HRHU', ' URH   HRU ', '  RUUUUUR  ', '  R     R  ', '  R     R  ', '           ')
            .aisle('CRRCCCCCRRC', 'G  H   H  G', 'UHHH   HHHU', ' UHH   HHU ', '  UHHHHHU  ', '    UUU    ', '           ', '           ')
            .aisle('CRRCCCCCRRC', 'G   CGC   G', 'U   CGC   U', ' U  CGC  U ', '  UHCCCHU  ', '   UGGGU   ', '           ', '           ')            
            .aisle('CCCCCCCCCCC', 'G   GFG   G', 'U   GFG   U', ' U  GFG  U ', '  UHCFCHU  ', '   UGFGU   ', '     B     ', '           ')            
            .aisle('CRRCCCCCRRC', 'G   CGC   G', 'U   CGC   U', ' U  CGC  U ', '  UHCCCHU  ', '   UGGGU   ', '           ', '           ')
            .aisle('CRRCCCCCRRC', 'G  H   H  G', 'UHHH   HHHU', ' UHH   HHU ', '  UHHHHHU  ', '    UUU    ', '           ', '           ')
            .aisle('CRRRRCRRRRC', 'G         G', 'UHRH   HRHU', ' URH   HRU ', '  RUUUUUR  ', '  R     R  ', '  R     R  ', '           ')
            .aisle('CRRRRCRRRRC', 'G         G', 'UHHH   HHHU', '  UUUUUUU  ', '           ', '           ', '           ', '           ')
            .aisle('CCCCCKCCCCC', 'CGGGGGGGGGC', 'CUUUUUUUUUC', 'C         C', 'C         C', 'C         C', 'C         C', 'C         C')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('B', Predicates.blocks('bloodmagic:altar'))            
            .where('R', Predicates.blocks('bloodmagic:bloodstonebrick'))
            .where('U', Predicates.blocks('bloodmagic:blankrune')
                .or(Predicates.blocks('bloodmagic:speedrune'))
                .or(Predicates.blocks('bloodmagic:sacrificerune'))
                .or(Predicates.blocks('bloodmagic:selfsacrificerune'))
                .or(Predicates.blocks('bloodmagic:dislocationrune'))
                .or(Predicates.blocks('bloodmagic:altarcapacityrune'))
                .or(Predicates.blocks('bloodmagic:bettercapacityrune'))
                .or(Predicates.blocks('bloodmagic:orbcapacityrune'))
                .or(Predicates.blocks('bloodmagic:accelerationrune'))
                .or(Predicates.blocks('bloodmagic:chargingrune'))
            )
            .where('F', Predicates.blocks('gtceu:hv_hermetic_casing'))            
            .where('H', Predicates.blocks('gtceu:hsla_steel_frame'))
            .where('G', Predicates.blocks('botania:bifrost_perm'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))	
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
			)
            .where(' ', Predicates.any()) 
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/distillation_tower')
})
