GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('seed_fabricator')
        .category('fabricator')
        .setEUIO('in') // Machine takes power IN
        .setMaxIOSize(9, 1, 3, 3) // 4 Item In, 1 Item Out, 2 Fluid In
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)	
})

GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('seed_fabricator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('seed_fabricator') 
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()            
			.aisle('CCCCCCC', 'CGGGGGC', 'CCCCCCC', '   P   ')
			.aisle('CCCCCCC', 'G     G', 'CCCCCCC', ' P   P ')
			.aisle('CCCCCCC', 'G     G', 'CCCCCCC', '       ')
			.aisle('CCCCCCC', 'G  W  G', 'CCCCCCC', 'P  A  P')
			.aisle('CCCCCCC', 'G     G', 'CCCCCCC', '       ')
			.aisle('CCCCCCC', 'G     G', 'CCCCCCC', ' P   P ')
			.aisle('CCCKCCC', 'CGGGGGC', 'CCCCCCC', '   P   ')
			.where('W', Predicates.blocks('mysticalagriculture:awakened_supremium_block'))
            .where('A', Predicates.blocks('mysticalagriculture:infusion_altar'))
            .where('P', Predicates.blocks('mysticalagriculture:infusion_pedestal'))
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('botania:bifrost_perm'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))	
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
			)
            .where(' ', Predicates.any()) 
            .build()
        )
		.workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')			
})