


GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    
    allthemods.create('water_filtration_plant')
        .category('water_filtration_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 0, 1, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('ozonation_plant')
        .category('ozonation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('flocculation_plant')
        .category('flocculation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 2)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)
    
    allthemods.create('microbial_filtration_array')
        .category('microbial_filtration_array')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('laser_purification')
        .category('laser_purification')
        .setEUIO('in')
        .setMaxIOSize(12, 12, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('cryogenic_unit')
        .category('cryogenic_unit')
        .setEUIO('in')
        .setMaxIOSize(12, 12, 12, 12)
        .setSound(GTSoundEntries.COOLING)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CRYSTALLIZATION, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('baryonic_stabilizer')
        .category('baryonic_stabilizer')
        .setEUIO('in')
        .setMaxIOSize(6, 0, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)
    
    allthemods.create('baryonic_separator')
        .category('baryonic_separator')
        .setEUIO('in')
        .setMaxIOSize(2, 6, 0, 0)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('psycho_fraculator')
        .category('psycho_fraculator')
        .setEUIO('in')
        .setMaxIOSize(6, 12, 3, 0)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('hydro_electromagnetic_separator')
        .category('hydro_electromagnetic_separator')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.ELECTROLYZER)        
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('fractional_gas_separator')
        .category('fractional_gas_separator')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.ELECTROLYZER)        
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)

});




GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('water_filtration_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('water_filtration_plant')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' CCC ', ' CCC ', ' CCC ', ' CCC ', ' CCC ')
            .aisle('CCCCC', 'CCFCC', 'CCFCC', 'CCFCC', 'CCCCC')
            .aisle('CCCCC', 'CFFFC', 'CFFFC', 'CFFFC', 'CCCCC')
            .aisle('CCCCC', 'CCFCC', 'CCFCC', 'CCFCC', 'CCCCC')
            .aisle(' CCC ', ' CKC ', ' CCC ', ' CCC ', ' CCC ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))            
            .where('F', Predicates.blocks('gtceu:filter_casing'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')                
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1)))                    
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')

    allthemods.create('ozonation_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('ozonation_plant')
        .appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ')
            .aisle('     CCCCC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CCCCC ')    
            .aisle('CCCCCCCCCCC', 'CCCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', '    CCCCCCC')
            .aisle('CCCCCCCCCCC', 'C      P  C', 'CPPPPPPP  C', 'C      P  C', 'CCCCC  P  C', '    CCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCC   CC', 'CKCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', '    CCCCCCC')
            .aisle('     CCCCC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CCCCC ')
            .aisle('      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('P', Predicates.blocks('gtceu:titanium_pipe_casing'))
            .where('C', Predicates.blocks('gtceu:stable_machine_casing')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
            )
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/multiblock/large_chemical_reactor')
        
   allthemods.create('flocculation_plant', 'multiblock')
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType('flocculation_plant')
            .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
            .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
            .pattern(definition => FactoryBlockPattern.start()
                .aisle(' CCC    CCC    CCC ', ' CCC    NCN    CCC ', ' CCC    CCC    CCC ')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle('CCCCC   CCC   CCCCC', 'E   PPPPPPPPPPP   I', 'CFFFC   CCC   CFFFC')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle(' CCC    CCC    CCC ', ' CCC    CPC    CCC ', ' CCC    CCC    CCC ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle(' CCC    CCC    CCC ', ' CCC    CPC    CCC ', ' CCC    CCC    CCC ')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle('CCCCC   CCC   CCCCC', 'E   PPPPPPPPPPP   I', 'CFFFC   CCC   CFFFC')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle(' CCC    CMC    CCC ', ' CCC    CKC    CCC ', ' CCC    CHC    CCC ')
                .where('E', Predicates.abilities(PartAbility.EXPORT_FLUIDS).setExactLimit(2))                        
                .where('I', Predicates.abilities(PartAbility.IMPORT_FLUIDS).setExactLimit(2))                
                .where('M', Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .where('H', Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
                .where('N', Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(2))
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('F', Predicates.blocks('gtceu:filter_casing'))
                .where('C', Predicates.blocks('gtceu:clean_machine_casing'))
                .where('P', Predicates.blocks('gtceu:tungstensteel_pipe_casing'))
                .where(' ', Predicates.air())
                .build()
            )
        .workableCasingModel(
            'gtceu:block/casings/solid/machine_casing_clean_stainless_steel',
            'gtceu:block/multiblock/large_chemical_reactor'
        )
    
    allthemods.create('laser_purification', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('laser_purification')
        .appearanceBlock(GTBlocks.CASING_TUNGSTENSTEEL_ROBUST)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_robust_tungstensteel', 'gtceu:block/multiblock/large_engraving_laser')
    
 
    
    

    allthemods.create('microbial_filtration_array', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('microbial_filtration_array')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/multiblock/large_chemical_reactor')


    
    
    allthemods.create('cryogenic_unit', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('cryogenic_unit')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/vacuum_freezer')

    allthemods.create('baryonic_stabilizer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_stabilizer')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')
    
     allthemods.create('baryonic_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_separator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')

    allthemods.create('psycho_fraculator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('psycho_fraculator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')

        allthemods.create('hydro_electromagnetic_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('hydro_electromagnetic_separator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/assembly_line')

        allthemods.create('fractional_gas_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('fractional_gas_separator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/distillation_tower')
})