


GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    
    allthemods.create('water_filtration_plant')
        .category('water_filtration_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 0, 1, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('ozonation_plant')
        .category('ozonation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('flocculation_plant')
        .category('flocculation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 2)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)
    
    allthemods.create('microbial_filtration_array')
        .category('microbial_filtration_array')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('laser_purification')
        .category('laser_purification')
        .setEUIO('in')
        .setMaxIOSize(9, 9, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('cryogenic_unit')
        .category('cryogenic_unit')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 3, 3)
        .setSound(GTSoundEntries.COOLING)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CRYSTALLIZATION, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('baryonic_stabilizer')
        .category('baryonic_stabilizer')
        .setEUIO('in')
        .setMaxIOSize(6, 0, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)
    
    allthemods.create('baryonic_separator')
        .category('baryonic_separator')
        .setEUIO('in')
        .setMaxIOSize(3, 6, 3, 3)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('psycho_fraculator')
        .category('psycho_fraculator')
        .setEUIO('in')
        .setMaxIOSize(6, 12, 3, 0)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('hydro_electromagnetic_separator')
        .category('hydro_electromagnetic_separator')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 3, 3)
        .setSound(GTSoundEntries.ELECTROLYZER)        
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('fractional_gas_separator')
        .category('fractional_gas_separator')
        .setEUIO('in')
        .setMaxIOSize(3, 3, 6, 6)
        .setSound(GTSoundEntries.ELECTROLYZER)        
        .setProgressBar(GuiTextures.PROGRESS_BAR_EXTRACT, FillDirection.LEFT_TO_RIGHT)

});




GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('water_filtration_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('water_filtration_plant')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' CCC ', ' CCC ', ' CCC ', ' CCC ', ' CCC ')
            .aisle('CCCCC', 'CCFCC', 'CCFCC', 'CCFCC', 'CCCCC')
            .aisle('CCCCC', 'CFFFC', 'CFFFC', 'CFFFC', 'CCCCC')
            .aisle('CCCCC', 'CCFCC', 'CCFCC', 'CCFCC', 'CCCCC')
            .aisle(' CCC ', ' CKC ', ' CCC ', ' CCC ', ' CCC ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))            
            .where('F', Predicates.blocks('gtceu:filter_casing'))
            .where('C', Predicates.blocks('gtceu:clean_machine_casing')                
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1)))                    
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')

    allthemods.create('ozonation_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('ozonation_plant')
        .appearanceBlock(GTBlocks.CASING_TITANIUM_STABLE)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ')
            .aisle('     CCCCC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CCCCC ')    
            .aisle('CCCCCCCCCCC', 'CCCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', '    CCCCCCC')
            .aisle('CCCCCCCCCCC', 'C      P  C', 'CPPPPPPP  C', 'C      P  C', 'CCCCC  P  C', '    CCCCCCC')
            .aisle('CCCCCCCCCCC', 'CCCCCC   CC', 'CKCCCC   CC', 'CCCCCC   CC', 'CCCCCC   CC', '    CCCCCCC')
            .aisle('     CCCCC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CC CC ', '     CCCCC ')
            .aisle('      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ', '      CCC  ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('P', Predicates.blocks('gtceu:titanium_pipe_casing'))
            .where('C', Predicates.blocks('gtceu:stable_machine_casing')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
            )
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_stable_titanium', 'gtceu:block/multiblock/large_chemical_reactor')
        
   allthemods.create('flocculation_plant', 'multiblock')
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType('flocculation_plant')
            .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
            .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
            .pattern(definition => FactoryBlockPattern.start()
                .aisle(' CCC    CCC    CCC ', ' CCC    NCN    CCC ', ' CCC    CCC    CCC ')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle('CCCCC   CCC   CCCCC', 'E   PPPPPPPPPPP   I', 'CFFFC   CCC   CFFFC')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle(' CCC    CCC    CCC ', ' CCC    CPC    CCC ', ' CCC    CCC    CCC ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle('        CCC        ', '        CPC        ', '        CCC        ')
                .aisle(' CCC    CCC    CCC ', ' CCC    CPC    CCC ', ' CCC    CCC    CCC ')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle('CCCCC   CCC   CCCCC', 'E   PPPPPPPPPPP   I', 'CFFFC   CCC   CFFFC')
                .aisle('CCCCC   CCC   CCCCC', 'CC CC   CFC   CC CC', 'CCFCC   CCC   CCFCC')
                .aisle(' CCC    CMC    CCC ', ' CCC    CKC    CCC ', ' CCC    CHC    CCC ')
                .where('E', Predicates.abilities(PartAbility.EXPORT_FLUIDS).setExactLimit(2))                        
                .where('I', Predicates.abilities(PartAbility.IMPORT_FLUIDS).setExactLimit(2))                
                .where('M', Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .where('H', Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))
                .where('N', Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(2))
                .where('K', Predicates.controller(Predicates.blocks(definition.get())))
                .where('F', Predicates.blocks('gtceu:filter_casing'))
                .where('C', Predicates.blocks('gtceu:clean_machine_casing'))
                .where('P', Predicates.blocks('gtceu:tungstensteel_pipe_casing'))
                .where(' ', Predicates.any())
                .build()
            )
        .workableCasingModel(
            'gtceu:block/casings/solid/machine_casing_clean_stainless_steel',
            'gtceu:block/multiblock/large_chemical_reactor'
        )
    
    allthemods.create('laser_purification', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('laser_purification')
        .appearanceBlock(GTBlocks.MACHINE_CASING_ZPM)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCCCCC')
            .aisle('CCCCCCC', 'GL   LG', 'GL   LG', 'GL   LG', 'CCCCCCC')
            .aisle('CCCCCCC', 'G     G', 'G     G', 'G     G', 'CCCCCCC')
            .aisle('CCCCCCC', 'GL   LG', 'GL   LG', 'GL   LG', 'CCCCCCC')
            .aisle('CCCCCCC', 'G     G', 'G     G', 'G     G', 'CCCCCCC')
            .aisle('CCCCCCC', 'GL   LG', 'GL   LG', 'GL   LG', 'CCCCCCC')
            .aisle('CCCKCCC', 'CGGGGGC', 'CGGGGGC', 'CGGGGGC', 'CCCCCCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('G', Predicates.blocks('gtceu:fusion_glass'))
            .where('L', Predicates.blocks('gtceu:superconducting_coil'))
            .where('H', Predicates.blocks('gtceu:zpm_hermetic_casing'))
            .where('C', Predicates.blocks('gtceu:zpm_machine_casing')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
            )
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/voltage/zpm/side', 'gtceu:block/multiblock/vacuum_freezer')
    
 
    
    

    allthemods.create('microbial_filtration_array', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('microbial_filtration_array')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('CCCCC', ' GFG ', ' GFG ', ' GFG ', 'CCCCC')
            .aisle('CCCCC', ' F F ', ' F F ', ' F F ', 'CCCCC')
            .aisle('CCCCC', ' GFG ', ' GKG ', ' GFG ', 'CCCCC')
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .where('C', Predicates.blocks('gtceu:plascrete')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
            )
            .where('F', Predicates.blocks('gtceu:filter_casing'))            
            .where('G', Predicates.blocks('gtceu:cleanroom_glass'))
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/cleanroom/plascrete', 'gtceu:block/multiblock/vacuum_freezer')


    
    
    allthemods.create('cryogenic_unit', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('cryogenic_unit')
        .appearanceBlock(GTBlocks.CASING_ALUMINIUM_FROSTPROOF)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle(' CCC   CCC ', ' CCC   CCC ', ' CIC   CCC ', ' CCC   CCC ', ' CCC   CCC ')
            .aisle('CCCCC CCCCC', 'C   CCC   C', 'C   CCC   C', 'C   CCC   C', 'CCCCC CCCCC')
            .aisle('CCCCC CCCCC', 'C   CCC   C', 'I         E', 'C   CCC   C', 'CCCCC CCCCC')
            .aisle('CCCCC CCCCC', 'C   CCC   C', 'C   CKC   C', 'C   CCC   C', 'CCCCC CCCCC')
            .aisle(' CCC   CCC ', ' CCC   CCC ', ' CIC   CCC ', ' CCC   CCC ', ' CCC   CCC ')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('E', Predicates.abilities(PartAbility.EXPORT_FLUIDS).setExactLimit(1))                        
            .where('I', Predicates.abilities(PartAbility.IMPORT_FLUIDS).setExactLimit(3))
            .where('C', Predicates.blocks(GTBlocks.CASING_ALUMINIUM_FROSTPROOF.get())       			                
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
			)
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_frost_proof', 'gtceu:block/multiblock/vacuum_freezer')

    allthemods.create('baryonic_stabilizer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_stabilizer')
        .appearanceBlock(GTBlocks.FUSION_CASING_MK3)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('CCCCC', 'CGGGC', 'CGGGC', 'CGGGC', 'CCCCC')                    
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('CMMMC', 'M   M', 'M   M', 'M   M', 'CMMMC')
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('CMMMC', 'M   M', 'M   M', 'M   M', 'CMMMC')
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('COOOC', 'O   O', 'O   O', 'O   O', 'COOOC')
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('CMMMC', 'M   M', 'M   M', 'M   M', 'CMMMC')
            .aisle('CCCCC', 'C   C', 'C   C', 'C   C', 'CCCCC')
            .aisle('CMMMC', 'M   M', 'M   M', 'M   M', 'CMMMC')
            .aisle('CCCCC', 'CGCGC', 'CCKCC', 'CGCGC', 'CCCCC')            
            .where('M', Predicates.blocks('gtceu:uhv_machine_casing')) 
            .where('O', Predicates.blocks('gtceu:fusion_coil')) 
            .where('G', Predicates.blocks('gtceu:fusion_glass')) 
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('C', Predicates.blocks('gtceu:fusion_casing_mk3')
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
            )
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/fusion/fusion_casing_mk3', 'gtceu:block/multiblock/fusion_reactor')
    
     allthemods.create('baryonic_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_separator')
        .appearanceBlock(GTBlocks.PLASTCRETE)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()                                            
            .aisle('               ', '      CCC      ', '               ')
            .aisle('      SSS      ', '    CC   CC    ', '      SSS      ')
            .aisle('    CC   CC    ', '   C  CCC  C   ', '    CC   CC    ')
            .aisle('   C       C   ', '  C CC   CC C  ', '   C       C   ')
            .aisle('  C         C  ', ' C C       C C ', '  C         C  ')
            .aisle('  C         C  ', ' C C       C C ', '  C         C  ')
            .aisle(' S           S ', 'C C         C C', ' S           S ')    
            .aisle(' S           S ', 'C C         C C', ' S           S ')
            .aisle(' S           S ', 'C C         C C', ' S           S ')
            .aisle('  C         C  ', ' C C       C C ', '  C         C  ')
            .aisle('  C         C  ', ' C C       C C ', '  C         C  ')
            .aisle('   C       C   ', '  C CC   CC C  ', '   C       C   ')
            .aisle('    CC   CC    ', '   C  CCC  C   ', '    CC   CC    ')
            .aisle('      SSS      ', '    CC   CC    ', '      SSS      ')
            .aisle('               ', '      CKC      ', '               ')            
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))                                                                                    
            .where('S', Predicates.blocks('gtceu:superconducting_coil'))
            .where('C', Predicates.blocks(GTBlocks.PLASTCRETE.get())      
                .or(Predicates.autoAbilities(definition.getRecipeTypes())) 			                                   
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
			)
            .where(' ', Predicates.any()) 
            .build()
        )
        .workableCasingModel('gtceu:block/casings/cleanroom/plascrete', 'gtceu:block/multiblock/research_station')

    allthemods.create('hydro_electromagnetic_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('hydro_electromagnetic_separator')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()            
            .aisle('F       F', 'F  CCC  F', 'FFFCCCFFF', 'F  CCC  F', 'F   F   F', 'F   F   F', 'FFFFFFFFF')
            .aisle('         ', '         ', 'F       F', '         ', '         ', '         ', 'F   F   F')
            .aisle('  BBBBB  ', '  BGGGB  ', 'F BGGGB F', '  BGGGB  ', '  BBBBB  ', '         ', 'F   F   F')
            .aisle('  BBBBB  ', 'C G   G C', 'C G   G C', 'C G   G C', '  BBBBB  ', '         ', 'F   F   F')
            .aisle('  BBBBB  ', 'C G   G C', 'C G   G C', 'C G   G C', '  BBBBB  ', 'F   F   F', 'FFFFFFFFF')
            .aisle('  BBBBB  ', 'C G   G C', 'C G   G C', 'C G   G C', '  BBBBB  ', '         ', 'F   F   F')
            .aisle('  BBBBB  ', '  BGGGB  ', 'F BGGGB F', '  BGGGB  ', '  BBBBB  ', '         ', 'F   F   F')
            .aisle('         ', '         ', 'F       F', '         ', '         ', '         ', 'F   F   F')
            .aisle('F       F', 'F  CCC  F', 'FFFCKCFFF', 'F  CCC  F', 'F   F   F', 'F   F   F', 'FFFFFFFFF')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('B', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get()))
            .where('F', Predicates.blocks('gtceu:aluminium_frame'))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes())) 			                                   
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
			)
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/distillation_tower')

        allthemods.create('psycho_fraculator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('psycho_fraculator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/assembly_line')

        allthemods.create('fractional_gas_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('fractional_gas_separator')
        .appearanceBlock(GTBlocks.CASING_STAINLESS_CLEAN)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('FFFFFFFFF', 'F   C   F', 'F   C   F', 'F   C   F', 'F   C   F', 'FFFFFFFFF')
            .aisle('FBBBFBBBF', ' BGBFBGB ', ' BGBFBGB ', ' BGBFBGB ', ' BGBFBGB ', 'FBBBFBBBF')
            .aisle('FBBBFBBBF', ' G G G G ', ' G G G G ', ' G G G G ', ' G G G G ', 'FBBBFBBBF')
            .aisle('FBBBFBBBF', ' BGB BGB ', ' BGB BGB ', ' BGB BGB ', ' BGB BGB ', 'FBBBFBBBF')
            .aisle('FFFFFFFFF', 'CF     FC', 'CF     FC', 'CF     FC', 'CF     FC', 'FFFFFFFFF')
            .aisle('FBBBFBBBF', ' BGB BGB ', ' BGB BGB ', ' BGB BGB ', ' BGB BGB ', 'FBBBFBBBF')
            .aisle('FBBBFBBBF', ' G G G G ', ' G G G G ', ' G G G G ', ' G G G G ', 'FBBBFBBBF')
            .aisle('FBBBFBBBF', ' BGBFBGB ', ' BGBFBGB ', ' BGBFBGB ', ' BGBFBGB ', 'FBBBFBBBF')
            .aisle('FFFFFFFFF', 'F   C   F', 'F   K   F', 'F   C   F', 'F   C   F', 'FFFFFFFFF')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where('B', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get()))
            .where('F', Predicates.blocks('gtceu:aluminium_frame'))
            .where('G', Predicates.blocks('gtceu:tempered_glass'))
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes())) 			                                   
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setExactLimit(1))                
			)
            .where(' ', Predicates.any())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/distillation_tower')
})