


GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('water_filtration_plant')
        .category('water_filtration_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 0, 1, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('ozonation_plant')
        .category('ozonation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 1)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('flocculation_plant')
        .category('flocculation_plant')
        .setEUIO('in')
        .setMaxIOSize(0, 0, 2, 2)
        .setSound(GTSoundEntries.CHEMICAL)
        .setProgressBar(GuiTextures.PROGRESS_BAR_DISTILLATION_TOWER, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('laser_purification')
        .category('laser_purification')
        .setEUIO('in')
        .setMaxIOSize(12, 12, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('cryogenic_unit')
        .category('cryogenic_unit')
        .setEUIO('in')
        .setMaxIOSize(12, 12, 12, 12)
        .setSound(GTSoundEntries.COOLING)
        .setProgressBar(GuiTextures.PROGRESS_BAR_CRYSTALLIZATION, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('baryonic_stabilizer')
        .category('baryonic_stabilizer')
        .setEUIO('in')
        .setMaxIOSize(6, 0, 1, 1)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)
    
    allthemods.create('baryonic_separator')
        .category('baryonic_separator')
        .setEUIO('in')
        .setMaxIOSize(2, 6, 0, 0)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

    allthemods.create('psycho_fraculator')
        .category('psycho_fraculator')
        .setEUIO('in')
        .setMaxIOSize(6, 12, 3, 0)
        .setSound(GTSoundEntries.SCIENCE)
        .setProgressBar(GuiTextures.PROGRESS_BAR_MASS_FAB, FillDirection.LEFT_TO_RIGHT)

});

/*
.where('P', Predicates.blocks(''))                        
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))	
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
            )
                */


GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('water_filtration_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('water_filtration_plant')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')

    allthemods.create('ozonation_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('ozonation_plant')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')

    allthemods.create('flocculation_plant', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('flocculation_plant')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')
    
    allthemods.create('laser_purification', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('laser_purification')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_engraving_laser')
    
    allthemods.create('cryogenic_unit', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('cryogenic_unit')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/vacuum_freezer')

    allthemods.create('baryonic_stabilizer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_stabilizer')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')
    
     allthemods.create('baryonic_separator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('baryonic_separator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')

    allthemods.create('psycho_fraculator', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('psycho_fraculator')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('K')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.air())
            .build()
        )
        .workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/research_station')
})