#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 03 23:24:24 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.6.1.zip
