#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Thu Jul 30 01:57:36 EDT 2026
=======
#Thu Jul 30 00:26:25 EDT 2026
>>>>>>> 00e2d1c8c566224d4d6d354e223933263f9da38f
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.6.1.zip
enableShaders=false
