#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 31 12:26:46 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.6.1.zip
