GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('bio_electrical_infuser')
        .category('infuser')
        .setEUIO('in') // Machine takes power IN
        .setMaxIOSize(16, 1, 8, 4)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)	
})

GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('bio_electrical_infuser', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('bio_electrical_infuser') 
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()            
			.aisle('CCC', 'CBC', 'CBC', 'CBC', 'CCC')
			.aisle('CCC', 'B B', 'BIB', 'B B', 'CCC')
			.aisle('CKC', 'CBC', 'CBC', 'CBC', 'CCC')
			.where('B', Predicates.blocks('botania:bifrost_perm'))
            .where('I', Predicates.blocks('evilcraft:blood_infuser'))            
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))            
            .where('C', Predicates.blocks(GTBlocks.CASING_STAINLESS_CLEAN.get())
				.or(Predicates.autoAbilities(definition.getRecipeTypes()))	
				.or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))				
			)
            .where(' ', Predicates.air()) 
            .build()
        )
		.workableCasingModel('gtceu:block/casings/solid/machine_casing_clean_stainless_steel', 'gtceu:block/multiblock/large_chemical_reactor')			
})